// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlnPsWWE5dAklZCufSV2QOz7ysyA0Zjxw',
    appId: '1:616458751235:android:3f2c3f7dd45aaaaa6fad36',
    messagingSenderId: '616458751235',
    projectId: 'nepal-wanderer',
    databaseURL: 'https://nepal-wanderer-default-rtdb.firebaseio.com',
    storageBucket: 'nepal-wanderer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_N5jnFaclBKBXq8vV0YL8bm4fEzr1Vyk',
    appId: '1:616458751235:ios:c90773c51150624e6fad36',
    messagingSenderId: '616458751235',
    projectId: 'nepal-wanderer',
    databaseURL: 'https://nepal-wanderer-default-rtdb.firebaseio.com',
    storageBucket: 'nepal-wanderer.appspot.com',
    iosBundleId: 'com.nepalwanderer.nepalWanderer',
  );
}
